= Continuity of Functions =
:doctype: book
:stem: latexmath
:eqnums:
:toc:

When is a function said continuous? What conditions must a function satisfy to be considered continuous?

== Definition of Continuity ==
A function stem:[f: \mathbb{R}^n \to \mathbb{R}^m] is continuous at stem:[\mathbf{x}_0 \in \text{dom } f] if

* stem:[f] is defined at stem:[\mathbf{x}_0].
* The limit stem:[\lim_{\mathbf{x} \to \mathbf{x}_0} f(\mathbf{x})] exists.
* The limit equals the function value, stem:[\lim_{\mathbf{x} \to \mathbf{x}_0} f(\mathbf{x}) = f(\mathbf{x}_0)].

A function is continuous if it is continuous at every point of its domain. An alternate definition of continuity is as follows.

*stem:[\delta-\epsilon] definition of continuity:*

A function stem:[f: \mathbb{R}^n \to \mathbb{R}^m] is continuous at stem:[\mathbf{x}_0 \in \text{dom } f] if for all stem:[\epsilon > 0] there exists a stem:[\delta] such that

[stem]
++++
\mathbf{x} \in \text{dom } f, \hspace{1cm} \|\mathbf{x} -  \mathbf{x}_0\|_2 \leq \delta \implies \|f(\mathbf{x}) - f(\mathbf{x}_0) \|_2 \leq \epsilon
++++

Continuity can also be described in terms of limits: whenever the sequence stem:[\mathbf{x}_1, \mathbf{x}_2, \dots, \in \text{dom } f ] converges to a point stem:[\mathbf{x}_0 \in \text{dom } f], the sequence stem:[f(\mathbf{x}_1), f(\mathbf{x}_2), \dots,] converges to stem:[f(\mathbf{x}_0)], i.e.,

[stem]
++++
f(\lim_{n \to \infty} \mathbf{x}_n) = \lim_{n \to \infty} f(\mathbf{x}_n) 
++++

====
A function stem:[f] is continuous at stem:[\mathbf{x}_0 \in \text{dom } f] iff for any sequence stem:[\{\mathbf{x_n}\} \rightarrow \mathbf{x}_0], we have stem:[\{f(\mathbf{x_n})\}\rightarrow f(\mathbf{x}_0)].
====

* Take any sequence stem:[\{\mathbf{x_n}\}] that converges to this stem:[\mathbf{x}_0].
* For each element in the sequence, compute the corresponding function value stem:[\{f(\mathbf{x_n})\}]. This is a sequence of real numbers. This should converge to stem:[f(\mathbf{x}_0)]. If this happens for any sequence stem:[\{\mathbf{x_n}\}] converging to stem:[\mathbf{x}_0], then we say the function stem:[f] is continuous at stem:[\mathbf{x}_0].

== Lipschitz Continuity ==
This is a stronger notion of continuity. All Lipschitz Continuous functions are continuous, but not all continuous functions are Lipschitz continuous. A function stem:[f: \mathbb{R}^n \rightarrow \mathbb{R}^m] is stem:[L]-Lipschitz continuous iff

[stem]
++++
\| f(\mathbf{x}) - f(\mathbf{y}) \| \leq L \| \mathbf{x} - \mathbf{y} \| \hspace{1cm} \forall \mathbf{x}, \mathbf{y} \in \text{dom } f
++++

where stem:[L] is a positive real number, stem:[0 < L < \infty]. Note that, the norm appearing in the LHS and RHS do not need to be the same if the domain and co-domain belong to different spaces.

Take any two points stem:[\mathbf{x}, \mathbf{y} \in \text{dom } f], look at their difference in the function values. If the difference in the function values is not too high with respect to how far the points themselves are, i.e., if we are able to bound the function growth in terms of the distance between the points, then the function is Lipschitz continuous.

The stem:[L] tells us how fast the function grows. The higher the stem:[L], the steeper the function will be. If stem:[L] is zero, the function is not growing at all.

*Example 01:* 

Let stem:[f(x) = 2x+3]. To show that the function is Lipschitz continuous, we need to find a bound stem:[L].

[stem]
++++
|f(x) - f(y) | = |2x+3 - 2y-3| = |2x-2y| = 2|x-y|
++++

Then stem:[|f(x) - f(y)| \leq 2|x-y|]. The function is 2-Lipschitz continuous. As we can observe the Lipschitz constant for a simple linear function is just its slope.

NOTE: We can also write stem:[|f(x) - f(y)| \leq 4|x-y|, \leq 5|x-y|, \dots]. But here we are looking for the least stem:[L].

*Example 02:* 

Let stem:[f(\mathbf{x}) = \mathbf{w}^\top \mathbf{x}], which is a linear function that takes n-dimensional input and outputs a real number. To show that the function is Lipschitz continuous, we need to find a bound stem:[L].

[stem]
++++
|f(\mathbf{x}) - f(\mathbf{y})| = | \mathbf{w}^\top \mathbf{x} -  \mathbf{w}^\top \mathbf{y}| = | \mathbf{w}^\top (\mathbf{x-y})| \leq \|\mathbf{w}\| \|\mathbf{x-y}\|
++++

The last inequality is by the Cauchy-Schwartz inequality.

*Example 03:* 

Let stem:[f(\mathbf{x}) = \mathbf{A} \mathbf{x}], which is a linear function that takes n-dimensional input and outputs a m-dimensional vector. Let stem:[\mathbf{A}] be a symmetric matrix. To show that the function is Lipschitz continuous, we need to find a bound stem:[L], which is a scalar.

[stem]
++++
\|\mathbf{Ax} - \mathbf{Ay} \| = \|\mathbf{A} (\mathbf{x} - \mathbf{y}) \|
++++

* By SVD, we can write stem:[\mathbf{A} = \sum_{i=1}^r \sigma_i \mathbf{u}_i \mathbf{v}_i^\top].
* stem:[(\mathbf{x} - \mathbf{y})] is a vector in the input space, stem:[\mathbb{R}^n]. So it can be written as stem:[\mathbf{x} - \mathbf{y} = \sum_{j=1}^n \lambda_j \mathbf{v}_j].

[stem]
++++
\begin{align*}
\mathbf{A} (\mathbf{x} - \mathbf{y}) & = \sum_{i=1}^r \sigma_i \mathbf{u}_i \mathbf{v}_i^\top \sum_{j=1}^n \lambda_j \mathbf{v}_j \\
& = \sum_{i=1}^r \sum_{j=1}^n \lambda_j \sigma_i \mathbf{u}_i \mathbf{v}_i^\top \mathbf{v}_j \\
& = \sum_{i=1}^r \lambda_i \sigma_i \mathbf{u}_i && \text{ as } V \text{ vectors are orthogonal } \\
\end{align*}
++++

This is just a linear combination of stem:[\mathbf{u}_i]'s. Then

[stem]
++++
\begin{align*}
\| \mathbf{A} (\mathbf{x} - \mathbf{y}) \| & = \|\sum_{i=1}^r \lambda_i \sigma_i \mathbf{u}_i \| \\
& = \sqrt{ \langle \sum_{i=1}^r \lambda_i \sigma_i \mathbf{u}_i, \sum_{i=1}^r \lambda_i \sigma_i \mathbf{u}_i \rangle} = \sqrt{ (\sum_{i=1}^r \lambda_i \sigma_i \mathbf{u}_i)^\top (\sum_{i=1}^r \lambda_i \sigma_i \mathbf{u}_i )} \\
& = \sqrt{ \sum_{i=1}^r \lambda_i \sigma_i \mathbf{u}_i^\top (\sum_{i=1}^r \lambda_i \sigma_i \mathbf{u}_i )} = \sqrt{ \sum_{i=1}^r \lambda_i^2 \sigma_i^2 } \\
\end{align*}
++++

Here stem:[\lambda_i] changes as per the vector stem:[(\mathbf{x} - \mathbf{y})], the stem:[\sigma_i] are fixed.

[stem]
++++
\begin{align*}
\| \mathbf{A} (\mathbf{x} - \mathbf{y}) \| & \leq \sqrt{ \sum_{i=1}^r \lambda_i^2 \sigma^2_{max} } \\
& = \sqrt{ \sigma^2_{max} \sum_{i=1}^r \lambda_i^2} = \sigma_{max} \sqrt{ \sum_{i=1}^r \lambda_i^2}
\end{align*}
++++

as singular values are always non-negative, stem:[\sqrt{ \sigma^2_{max}} = \sigma_{max}].

NOTE: For example: stem:[\sqrt{3\lambda_1^2 + 4\lambda_2^2} \leq \sqrt{4\lambda_1^2 + 4\lambda_2^2} = \sqrt{4} \sqrt{\lambda_1^2 + \lambda_2^2}]

Hence, we are able to show stem:[\| \mathbf{A} (\mathbf{x} - \mathbf{y}) \| \leq \sigma_{max} \|\mathbf{x} - \mathbf{y} \|]. Thus the Lipschitz constant is the highest singular value of the matrix stem:[\mathbf{A}].

*Example 04:* 

Let stem:[f(x) = x^2]. To show that the function is Lipschitz continuous, we need to find a bound stem:[L].

stem:[|x^2 -y^2| = |x+y| |x-y|]. This quantity can never be 

[stem]
++++
|x+y| |x-y| \not \leq L | x-y|
++++

For any given stem:[L], we can pick stem:[x,y] such that stem:[|x+y| > L]. So by contradiction, we say that this function stem:[f] is not Lipschitz continuous. This happens because the function grows too steeply compared to how stem:[x] grows.

But we restrict the domain of the function to stem:[x \in [-1,1\]]. Then the function is Lipschitz continuous because stem:[|x+y|] is upper bounded by 2. So the Lipschitz constant is 2.

====
Theorem that helps us find the Lipschitz constant:

If stem:[f] is differentiable, then say the magnitude of the derivative is bounded by some number, stem:[|f'(\mathbf{x})| \leq L] for all stem:[\mathbf{x} \in \text{dom } f]. Then such a number stem:[L] is the Lipschitz constant.
====

*Example 05:* 

Let stem:[f(x) = x \log x] where stem:[x >0]. Then stem:[f'(x) = 1 + \log x]. We need to find a constant such that stem:[|1 + \log x| \leq L] for all stem:[x>0]. We cannot find such a stem:[L]. Hence the function stem:[f(x)] is not Lipschitz continuous.

[bibliography]
== References ==

* Boyd, S. P., & Vandenberghe, L. (2004). Convex Optimization. Cambridge University Press.