= Properties of MPs =
:doctype: book
:author: Bharath Kumar S P
:email: bharath030195@gmail.com
:stem: latexmath
:eqnums:
:toc:

== Cascaded MPs ==
Say we are given a MP

[stem]
++++
\min_{\mathbf{w} \in \mathbb{R}^n} \hspace{1cm} \mathbf{w}^\top \mathbf{x} + b 
++++

Here the variable of the MP is stem:[\mathbf{w}]. And stem:[\mathbf{x}] and stem:[b] are given, fixed constant. They are known as *parameters* of the MP. The parameters of the MP are variables that are not variables of the MP. The value of the MP is a function of its parameters, i.e., the value of the MP depends on stem:[\mathbf{x}] and stem:[b]. 

*Example 01:*

[stem]
++++
\min_{\|\mathbf{w}\| \leq 1} \hspace{1cm} \mathbf{w}^\top \begin{bmatrix} 2 \\ 3 \end{bmatrix}  + 5
++++

The dot product of two vectors will be the least when the vectors are in the opposite direction, so out of all the directions we choose the vector stem:[ \begin{bmatrix} \frac{-2}{\sqrt{13}} \\ \frac{-3}{\sqrt{13}} \end{bmatrix}] which gives the value of the MP.

[stem]
++++
\begin{bmatrix} \frac{-2}{\sqrt{13}} \\ \frac{-3}{\sqrt{13}} \end{bmatrix}^\top \begin{bmatrix} 2 \\ 3 \end{bmatrix}  + 5 = -\sqrt{13} + 5
++++

Changing the values of stem:[\mathbf{x}] and stem:[b] gives us different value for the MP. Thus

[stem]
++++
g(\mathbf{x}, b) = \min_{\|\mathbf{w}\| \leq 1} \mathbf{w}^\top \mathbf{x} + b 
++++

In this case, we can write the function in the analytical form. Here the stem:[g(\mathbf{x}, b)] can be written analytically in terms of stem:[\mathbf{x}] and stem:[b]

[stem]
++++
g(\mathbf{x}, b) = \frac{-\mathbf{x}^\top}{\| \mathbf{x}\|} \mathbf{x} + b = - \|\mathbf{x}\| + b
++++

So it turns out that

====
[stem]
++++
\min_{\|\mathbf{w}\| \leq 1} \mathbf{w}^\top \mathbf{x} + b = - \|\mathbf{x}\| + b
++++
====

Since this is also a function, we can also ask stem:[\min_{\|\mathbf{x}\| \leq 1}  b  - \|\mathbf{x}\| = b-1]. Cascading both the results, we get

[stem]
++++
\min_{\|\mathbf{x}\| \leq 1}  \min_{\|\mathbf{w}\| \leq 1} \mathbf{w}^\top \mathbf{x} + b = b-1
++++

We can have such cascaded MPs. Start with evaluating the inner most MP. This gives us a function of the parameters. Then keep doing it. We can also do

[stem]
++++
\min_{b \geq 2} \min_{\|\mathbf{x}\| \leq 1}  \min_{\|\mathbf{w}\| \leq 1} \mathbf{w}^\top \mathbf{x} + b = 1
++++

=== Order of the MPs ===
In the cascaded MPs, the order doesn't matter. We can put the MPs in any order. All of them results in the same value for the MP. This is a theorem and can be proved. For example, let stem:[f(x,y)=x^2 + y^2].

[stem]
++++
\begin{align*}
\min_x \min_y f(x,y) & = \min_y \min_x f(x,y) = \min_{(x,y) \in \mathbb{R}^2} f(x,y)\\
\min_x x^2 & = \min_y y^2 \\
0 & = 0
\end{align*}
++++

We can't change the order when we have `min` and `max`. For example, stem:[\max_y \min_x f(x,y) \ne \min_x \max_y f(x,y)] (in general, it can be equal in some cases). We can always show that

[stem]
++++
\max_y \min_x f(x,y) \leq \min_x \max_y f(x,y)
++++

where the domain of both the variables is all the real numbers.

*Proof:*

[stem]
++++
\begin{align*}
f(x,y) & \leq \max_{y'} f(x,y') && \forall (x,y) \\
\min_x f(x,y) & \leq \min_x \max_{y'} f(x,y') && \forall y \\
\max_y \min_x f(x,y) & \leq \min_x \max_y f(x,y)
\end{align*}
++++

* By definition, the function value is always stem:[\leq] than stem:[\max_{y'} f(x,y')].
* Since the (1) inequality is true for all stem:[(x,y)], it is true for stem:[\min_x] as well. In the (2) inequality, the LHS is a function of stem:[y] and the RHS is a constant. The function of stem:[y] is less than or equal to a constant for all stem:[y].
* Since the (2) inequality is true for all stem:[y], it is also true for the `max` stem:[y] as well. If stem:[g(y) \leq 3 \,\, \forall y], then it is true that stem:[\max_y g(y) \leq 3].
